blog/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.main, name="main"),
    path('article/<int:num>/', views.article),
    path('edit-article/<int:num>/', views.edit_article,name="edart"),
    path('like/',views.like, name="like"),
    path('new-article/',views.write, name="write"),

    path('myprofile/', views.myprofile, name="profile"),
    path('myprofile/edit/', views.edit_profile, name="edit"),
        
    path('login/', views.login_view, name="login"),  
    path('logout/', views.logout_view, name="logout"),
    path('register/', views.register, name="register"),  
    path('admin/', admin.site.urls),
]

myblog/urls.py

from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

class Profile(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    bio=models.CharField(max_length=250,default='')
    img=models.ImageField(null=True,blank=True,default='johndoe.png')
    #img=models.CharField(default="johndoe.png", max_length=255)
    name=models.CharField(max_length=55,default='John Doe')
    

class Article(models.Model):
    author=models.ForeignKey(Profile,on_delete=models.CASCADE)
    likes=models.IntegerField(default=0)
    title=models.CharField(max_length=250)
    date=models.DateField(default=datetime.date.today)
    content=models.TextField()
    #img=models.CharField(null=True,blank=True,max_length=255)
    img=models.ImageField(null=True,blank=True)

class Likes(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    articleid=models.IntegerField()
    like=models.IntegerField(default=0) #1 if user liked
    

blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class WriteForm(forms.Form):
    title=forms.CharField(label="Title",required=True, max_length=250)
    img=forms.ImageField(required=False,)
    content=forms.CharField(label="Article",required=True,widget=forms.Textarea)


class LoginForm(forms.Form):
    username = forms.CharField(max_length=65)
    password = forms.CharField(max_length=65, widget=forms.PasswordInput)
    

class RegisterForm(UserCreationForm):
    class Meta:
        model=User
        fields = ['username','email','password1','password2']
        
class EditProfileForm(forms.Form):
    img=forms.ImageField(required=False,)
    name=forms.CharField(label="Name",required=True, max_length=250)
    bio=forms.CharField(label="Bio",required=True,widget=forms.Textarea)

    
    

blog/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required 
from django.contrib.auth import logout, login, authenticate
from django.http import HttpResponseRedirect, JsonResponse
from .forms import *
from .models import *
from django.core.files.storage import FileSystemStorage
import json 
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.views.decorators.cache import cache_page
from django.core.cache import cache
import logging
from myblog.settings import MEDIA_URL

logger= logging.getLogger('django')

@cache_page(60 * 15)
def main(request):
    page = request.GET.get('page', 1)
    articles=Article.objects.all()
    paginator = Paginator(articles, 10)
    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        articles = paginator.page(1)
    except EmptyPage:
        articles = paginator.page(paginator.num_pages)

    return render(request,"main.html",{"articles":articles,'mediaurl':MEDIA_URL})

#@cache_page(60 * 150)
def article(request,num):
    article=Article.objects.filter(id=num).first()
    nolike=0 #user can like
    edit=0
    cache.set('maincache',article,100*60)
    if not request.user.is_authenticated:
        return render(request,"article.html",{"article":article,"like":'',"nolike":1,"edit":edit,'mediaurl':MEDIA_URL})
    try:
        likes=Likes.objects.get(user=request.user,articleid=num)        
    except:
        likes=Likes.objects.create(user=request.user,articleid=num)
        likes.save()
    if request.user == article.author.user:
        edit=1 #allow editing
    return render(request,"article.html",{"article":article,"like":likes.like,"nolike":nolike,"edit":edit,'mediaurl':MEDIA_URL})


@login_required(login_url='/login/')
def write(request):
    logger.info('User '+str(request.user)+" visited new-article ")
    if request.method=='POST':
        form=WriteForm(request.POST,request.FILES)
        if form.is_valid():
            
            title=form.cleaned_data.get('title')
            content=form.cleaned_data.get('content')
            if request.FILES['img']:
                img = request.FILES['img'] #used to be image
                '''
                fs = FileSystemStorage()
                file_name = fs.save(image.name, image)
                file_url = fs.url(file_name)
                img=file_url'''
            else:
                img=''
            profile=Profile.objects.get(user=request.user)
            obj=Article.objects.create(author=profile,
                                       likes=0,
                                       title=title,
                                       content=content,
                                       img=img)
            obj.save()

            return HttpResponseRedirect('')
    else:
        form=WriteForm()
        return render(request,"write.html",{"form":form})
    
@login_required(login_url='/login/')
def myprofile(request):
    page = request.GET.get('page', 1)
    logger.info('User '+str(request.user)+" visited profile "+str(page))
    profile=Profile.objects.get(user=request.user)
    articles=Article.objects.filter(author=profile).all()
    paginator = Paginator(articles, 5)
    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        articles = paginator.page(1)
    except EmptyPage:
        articles = paginator.page(paginator.num_pages)

    return render(request,"myprofile.html",{"profile":profile, "articles":articles,'mediaurl':MEDIA_URL})


def login_view(request):
    if request.user.is_authenticated:
        return redirect('main')
    if request.method=="POST":
        form=LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request,username=username,password=password)
            if user:
                login(request, user)
                return redirect('main')
            else:
                return render(request, "login.html",{"form":LoginForm(),"msg":"Wrong username/password"})
                
    else:
        form=LoginForm()
        return render(request, "login.html",{"form":form})


def register(request):
    if request.user.is_authenticated:
        return redirect('main')
    if request.method=="POST":
        form=RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            profile=Profile.objects.create(user=user)
            profile.save()
            return redirect('login')
        else:
            return render(request, "register.html",{"form":RegisterForm(), "msg":"Please enter valid data",})
    else:
        form=RegisterForm()
        return render(request, "register.html",{"form":form})


def logout_view(request):
    if not request.user.is_authenticated:
        return redirect('login')
    else:
        logout(request)
        return redirect('main')


@login_required(login_url='/login/')
def like(request):
    data=json.loads(request.body)
    likes,created=Likes.objects.get_or_create(user=request.user,articleid=data['article'])

    if likes.like==0:
        likes.like=1
        article=Article.objects.get(id=data['article'])
        article.likes+=1
        article.save()
    else:
        likes.like=0
        article=Article.objects.get(id=data['article'])
        article.likes-=1
        article.save()
        
    likes.save()
    return JsonResponse({'foo':'bar'})
    
@login_required(login_url='/login/')
def edit_profile(request):
    if request.method=="POST":
        form=EditProfileForm(request.POST)
        if form.is_valid():
            name=form.cleaned_data.get('name')
            bio=form.cleaned_data.get('bio')
            profile=Profile.objects.get(user=request.user)
            img=profile.img
            if request.FILES['img']:
                img = request.FILES['img']
                '''fs = FileSystemStorage()
                file_name = fs.save(image.name, image)
                file_url = fs.url(file_name)
                img=file_url'''
            profile.name=name
            profile.bio=bio
            profile.img=img
            profile.save()
            return redirect('profile')
        else:
            profile=Profile.objects.get(user=request.user)
            context={"form":EditProfileForm(),
            "name":profile.name,
            "bio":profile.bio,}
            return render(request, "editprofile.html", context)
    else:
        profile=Profile.objects.get(user=request.user)
        context={"form":EditProfileForm(),
        "name":profile.name,
        "bio":profile.bio,}
        return render(request, "editprofile.html", context)


@login_required(login_url='/login/')
def edit_article(request,num):
    profile=Profile.objects.get(user=request.user)
    article=Article.objects.get(id=num)
    if profile.user != article.author.user:
        return redirect('main')
    
    if request.method=='POST':
        form=WriteForm(request.POST)
        if form.is_valid():
            img=article.img
            title=form.cleaned_data.get('title')
            content=form.cleaned_data.get('content')
            try:
                if request.FILES['img']:
                    img = request.FILES['img']
            except:
                pass
                '''fs = FileSystemStorage()
                file_name = fs.save(image.name, image)
                file_url = fs.url(file_name)
                img=file_url'''

            article.title=title
            article.content=content
            article.img=img
            article.save()
            return HttpResponseRedirect('')

        else:
            article=Article.objects.get(id=num)
            context={"form":WriteForm(), "title":article.title,
                 "content":article.content}
            return render(request,"editarticle.html",context)

    else:
        article=Article.objects.get(id=num)
        context={"form":WriteForm(), "title":article.title,
                 "content":article.content}
        return render(request,"editarticle.html",context)

blog/templates/article.html
{% include 'navbar.html' %}

<title> {{article.title}} </title>

</head>
<body> 
<input type="hidden" id="cart_token" name="cart_token" value="x">

<div>

{% if article.img == "" %}
{% else %}
<center><img src="{{mediaurl}}{{article.img}}" style="width:100%;height:200px;"></center>
{% endif %}
<br>
<center><div style="border: 3px solid ;width:50%">
<font style="font-size:35px;"> {{article.title}} </font> <br>

{% if edit == 1 %} <a href="..\..\edit-article\{{article.id}}"><button> Edit article </button></a> 

{% else %} {% endif %}

<font> {{article.author.name}} -- </font>
<font> {{article.date}} </font>
<br><br>

<p align="left">
<font style="font-size:20px;margin-left:4px;">
<article>
{{article.content}}
</article>
</font>
<br>

{% if nolike == 0 %} 
<button onclick="add_like({{article.id}})" style="float:left;" class="btn-info"> 
{% else %}
<button style="float:left;" class="btn-info">
{% endif %}

{% if nolike == 1 %}
<a href="{% url 'login' %}" style="text-decoration:none;color:white;"> Login to like </a>

{% elif like == 0 %}
like ! 


{% else %}
Unlike 

{% endif %}
</button>
<font style="float:right;"> likes: {{article.likes}} </font>
<br>
</p>
</article>
</div>
</body>

<script>

function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
const csrftoken = getCookie('csrftoken');

function add_like(a_id){
    console.log('User is logged in, sending data...')
    var url='/like/'

    fetch(url,{
        method:'POST',
        headers:{
            'Content-Type':'application/json',
            'X-CSRFToken':csrftoken,
        },
        body: JSON.stringify({'article':a_id})
        })

    .then((response)=>{
        return response.json()

      })

    .then((data) => {
        location.reload()
        //return 0 
    })

console.log("liked!")
}

</script>
{% include 'foot.html' %}

blog/templates/editarticle.html
{% include 'navbar.html' %}

<title> Write Article </title>

</head>
<body> 
<br><br><br>
<div style="border:5px solid black;width:45%;margin-left:20%;">
<form method="POST" enctype="multipart/form-data"><br>
    {% csrf_token %}
<center>   <label for="id_img">Img:</label>
    <input type="file" name="img" accept="image/*" id="id_img" value="0"><br><br>
    Title: <input type="text" name="title" value="{{title}}" > <br><br><br>
    <label for="id_content">Contents:</label><br>
    <textarea name="content" cols="40" rows="10" required="" id="id_content" style="width:500px;">{{content}}</textarea>
    <br>
    <input type="submit" value="Submit"></center>
</form>


</body>
</html>

blog/templates/editprofile.html
{% include 'navbar.html' %}

<title> Edit Profile </title>

</head>
<body> 

{% if msg %}
{{msg}}
{% endif %}
<br><br><br>
<div style="border:5px solid black;width:45%;margin-left:20%;">
<br>
<form method="POST" enctype="multipart/form-data" action="">
    {% csrf_token %}
 <center>   <label for="id_img">Img:</label>
    <input type="file" name="img" accept="image/*" id="id_img" value="0"><br><br>
    <label for="id_name">Name:</label>   <input type="text" name="name" id="id_name" value="{{name}}"> <br><br><br>
    <label for="id_bio">bio:</label><br>
    <textarea name="bio" cols="40" rows="10" required="" id="id_bio" style="width:500px;">{{bio}}</textarea>
    <br>
    <input type="submit" value="Submit">
</form>

</body>
</html>

blog/templates/foot.html
 <footer class="bg-dark text-white mt-4 py-3">
  <div class="container">
   <p>&copy; 2024 My Blog</p>
  </div>
 </footer>
</body>
</html>

blog/templates/login.html
{% include 'navbar.html' %}

<title> Write Article </title>

</head>
<body> 

{% if msg %}
{{msg}}
{% endif %}
  <div class="container">
    <div class="row justify-content-center mt-5">
      <div class="col-md-6">
        <div class="card">
          <div class="card-header">
            <h4>Login</h4>
          </div>
          <div class="card-body">
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
              <button type="submit" class="btn btn-primary">Login</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
<center>Dont have an account? <a href="{% url 'register' %}"> Register here! </a></center>




{% include 'foot.html' %}

blog/templates/main.html
{% include 'navbar.html' %}

<title> {{title}} </title>

</head>
<body> 

 <section class="container mt-4">
  <div class="row">

{% for article in articles %}


<div class="col-md-4 mb-4">
<a href="article/{{article.id}}" style="text-decoration: none;  color: black;">
    <div class="card">
<img src="{{mediaurl}}{{article.img}}" <!--style="width:130px;height:130px;"-- class="card-img-top">
<div class="card-body">
      <h2 class="card-title"> {{article.title}} </h2>
<font> {{article.author.name}} </font>
<font> {{article.date}} </font>
     </div>
    </div>
</a>
   </div>



{% endfor %}
</div>
</section>

{% if articles.has_other_pages %}
  <ul class="pagination">
    {% if articles.has_previous %}
      <li><a href="?page={{ articles.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in articles.paginator.page_range %}
      {% if articles.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if articles.has_next %}
      <li><a href="?page={{ articles..next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}


{% include 'foot.html' %}
 

blog/templates/myprofile.html
{% include 'navbar.html' %}

<title> {{article.title}} </title>

</head>
<body> 


<div class="container">
<div class="row mt-5">
<div class="col-md-4">
<img src="{{mediaurl}}{{profile.img}}" style="width:150px;height:150;">
</div>
<div class="col-md-7">
<h1>{{profile.name}}</h1>
<p class="lead">{{profile.bio}}</p>
<a href="{% url 'edit' %}"> <button class="btn-primary"> Edit profile </button> </a>
</div>
</div>
</div>
<br>


{% for article in articles %}

<a href="../article/{{article.id}}">
<div>
<img src="{{mediaurl}}{{article.img}}" style="width:130px;height:130px;">

<font> {{article.title}} </font>
<font> {{article.author.name}} </font>
<font> {{article.date}} </font>
</div>
</a>
{% endfor %}


{% if articles.has_other_pages %}
  <ul class="pagination">
    {% if articles.has_previous %}
      <li><a href="?page={{ articles.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in articles.paginator.page_range %}
      {% if articles.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if articles.has_next %}
      <li><a href="?page={{ articles..next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}



{% include 'foot.html' %}

blog/templates/navbar.html
<!DOCTYPE html>
<html>
<head>

 <title>My Blog</title>

  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}

  
</head>
<body>
 <header class="bg-dark text-white">
  <div class="container">
   <h1>My Blog</h1>
   <nav class="navbar navbar-expand-sm">
    <ul class="navbar-nav">

      <li class="nav-item">
<a href="{% url 'main' %}" class="text-light" style="text-decoration:none;"> Main </a>&nbsp;&nbsp;&nbsp;
</li>
   <li class="nav-item">
<a href="{% url 'write' %}" class="text-light" style="text-decoration:none;"> Write </a>&nbsp;&nbsp;&nbsp;
</li>
   <li class="nav-item">
<a href="#" class="text-light" style="text-decoration:none;"> Search </a>&nbsp;&nbsp;&nbsp;
</li>
{% if user.is_authenticated %}
   <li class="nav-item">
<a href="{% url 'profile' %}" class="text-light" style="text-decoration:none;"> My profile </a>&nbsp;&nbsp;&nbsp;
</li>
   <li class="nav-item">
<a href="{% url 'logout' %}" class="text-light" style="text-decoration:none;"> Logout </a>&nbsp;&nbsp;&nbsp;
</li>
{% else %}
   <li class="nav-item">
<a href="{% url 'login' %}" class="text-light" style="text-decoration:none;"> Login </a>&nbsp;&nbsp;&nbsp;
</li>
{% endif %}
</ul>
   </nav>
  </div>
 </header>


blog/templates/register.html
{% include 'navbar.html' %}

<title> My Blog - Register </title>

</head>
<body> 

{% if msg %}
{{msg}}
{% endif %}
  <div class="container">
    <div class="row justify-content-center mt-5">
      <div class="col-md-6">
        <div class="card">
          <div class="card-header">
            <h4>Register</h4>
          </div>
          <div class="card-body">
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
              <button type="submit" class="btn btn-primary">Register</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>



{% include 'foot.html' %}

blog/templates/write.html
{% include 'navbar.html' %}

<title> Write Article </title>

</head>
<body> 

  <div class="container">
    <div class="row justify-content-center mt-5">
      <div class="col-md-7">
        <div class="card">
          <div class="card-header">
            <center><h4>Write an article</h4></center>
          </div>
          <div class="card-body">
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
              <button type="submit" class="btn btn-primary">Post</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>



{% include 'foot.html' %}